import 'package:flutter/widgets.dart';

class SalesStrings {
  const SalesStrings._(this.languageCode);
  final String languageCode;

  static SalesStrings of(BuildContext context) =>
      SalesStrings._(Localizations.localeOf(context).languageCode);

  String call(String key) =>
      _values[languageCode]?[key] ?? _values['fr']![key] ?? key;

  static const _values = <String, Map<String, String>>{
    'fr': {
      'saleDetail': 'Détail vente',
      'invoiceDetail': 'Détail facture',
      'date': 'Date',
      'status': 'Statut',
      'ticket': 'Ticket',
      'products': 'Produits',
      'subtotal': 'Sous-total',
      'discount': 'Remise',
      'tax': 'TVA',
      'totalTtc': 'Total TTC',
      'paid': 'Montant payé',
      'paidShort': 'Payé',
      'due': 'Reste à payer',
      'dueShort': 'Reste',
      'paymentMethod': 'Mode de paiement',
      'payments': 'Paiements',
      'noPayment': 'Aucun paiement enregistré.',
      'edit': 'Modifier',
      'print': 'Imprimer',
      'reprint': 'Imprimer / Réimprimer',
      'payment': 'Paiement',
      'invoice': 'Facture',
      'viewPdf': 'Voir PDF',
      'delete': 'Supprimer',
      'retry': 'Réessayer',
      'paidStatus': 'Payée',
      'partialStatus': 'Partiellement payée',
      'unpaidStatus': 'Impayée',
      'unreconciledStatus': 'À rapprocher',
      'noPrinter': "Aucune imprimante n'est configurée.",
      'configurePrinter': 'Configurer une imprimante',
      'later': 'Plus tard',
      'printFailed': "Impossible d'imprimer la facture",
      'salePreserved': 'La vente reste enregistrée.',
      'sentToPrinter':
          "Facture envoyée à l'imprimante. Vérifiez la sortie papier.",
      'newSale': 'Nouvelle vente',
      'editSale': 'Modifier la vente',
      'clientSearch': 'Client (recherche)',
      'productSearch': 'Produit (recherche)',
      'packaging': 'Conditionnement',
      'unit': 'Unité',
      'quantity': 'Quantité',
      'serverPrice': 'Prix serveur',
      'addProduct': 'Ajouter produit',
      'payFull': 'Régler intégralement',
      'save': 'Enregistrer',
      'cash': 'Espèces',
      'cheque': 'Chèque',
      'transfer': 'Virement',
      'saleSaved': 'Vente enregistrée avec succès',
      'viewInvoice': 'Voir facture',
      'addPayment': 'Enregistrer paiement',
      'backSales': 'Retour aux ventes',
      'selectClientProducts': 'Sélectionnez le client et tous les produits.',
      'invalidQuantity': 'Quantité invalide',
      'invalidPrice': 'Prix invalide',
      'lineTotal': 'Total ligne',
      'displayedTotal': 'Total affiché',
      'newPayment': 'Nouveau paiement',
      'sale': 'Vente',
      'purchase': 'Achat',
      'amount': 'Montant',
      'documentId': 'Identifiant',
      'invalidIdentifier': 'Identifiant invalide',
      'invalidAmount': 'Montant invalide',
      'deleteSaleTitle': 'Supprimer cette vente ?',
      'deleteSaleWarning':
          "Cette action n'est pas une annulation métier et peut être refusée si des paiements existent.",
      'no': 'Non',
      'preview': 'Aperçu',
      'invoicePreview': 'Aperçu facture',
      'printFormat': "Format d'impression",
      'documentPreview': 'APERÇU DU DOCUMENT',
      'article': 'Article',
      'unitPrice': 'Prix unitaire',
      'total': 'Total',
      'client': 'Client',
      'phone': 'Téléphone',
      'address': 'Adresse',
      'thankYou': 'Merci pour votre confiance',
      'companyName': 'EL AMINE',
      'companyNameAr': 'الأمين للمواد الغذائية وغير الغذائية',
      'defaultPrinter': 'Imprimante par défaut',
      'openPdfToPrint': 'Ouvrir le PDF A4',
      'invoiceListHint': 'N° de facture ou client',
    },
    'ar': {
      'saleDetail': 'تفاصيل البيع',
      'invoiceDetail': 'تفاصيل الفاتورة',
      'date': 'التاريخ',
      'status': 'الحالة',
      'ticket': 'التذكرة',
      'products': 'المنتجات',
      'subtotal': 'المجموع الفرعي',
      'discount': 'الخصم',
      'tax': 'الضريبة',
      'totalTtc': 'الإجمالي شامل الضريبة',
      'paid': 'المبلغ المدفوع',
      'paidShort': 'المدفوع',
      'due': 'المبلغ المتبقي',
      'dueShort': 'المتبقي',
      'paymentMethod': 'طريقة الدفع',
      'payments': 'المدفوعات',
      'noPayment': 'لا توجد دفعات مسجلة.',
      'edit': 'تعديل',
      'print': 'طباعة',
      'reprint': 'طباعة / إعادة الطباعة',
      'payment': 'دفع',
      'invoice': 'فاتورة',
      'viewPdf': 'عرض PDF',
      'delete': 'حذف',
      'retry': 'إعادة المحاولة',
      'paidStatus': 'مدفوعة',
      'partialStatus': 'مدفوعة جزئياً',
      'unpaidStatus': 'غير مدفوعة',
      'unreconciledStatus': 'تحتاج إلى تسوية',
      'noPrinter': 'لا توجد طابعة مهيأة.',
      'configurePrinter': 'تهيئة طابعة',
      'later': 'لاحقاً',
      'printFailed': 'تعذرت طباعة الفاتورة',
      'salePreserved': 'تم حفظ البيع ولن يتم إلغاؤه.',
      'sentToPrinter': 'أُرسلت الفاتورة إلى الطابعة. تحقق من الورق.',
      'newSale': 'بيع جديد',
      'editSale': 'تعديل البيع',
      'clientSearch': 'البحث عن عميل',
      'productSearch': 'البحث عن منتج',
      'packaging': 'التعبئة',
      'unit': 'وحدة',
      'quantity': 'الكمية',
      'serverPrice': 'سعر الخادم',
      'addProduct': 'إضافة منتج',
      'payFull': 'دفع المبلغ كاملاً',
      'save': 'حفظ',
      'cash': 'نقداً',
      'cheque': 'شيك',
      'transfer': 'تحويل',
      'saleSaved': 'تم حفظ البيع بنجاح',
      'viewInvoice': 'عرض الفاتورة',
      'addPayment': 'تسجيل دفعة',
      'backSales': 'العودة إلى المبيعات',
      'selectClientProducts': 'اختر العميل وجميع المنتجات.',
      'invalidQuantity': 'الكمية غير صالحة',
      'invalidPrice': 'السعر غير صالح',
      'lineTotal': 'مجموع السطر',
      'displayedTotal': 'المجموع المعروض',
      'newPayment': 'دفعة جديدة',
      'sale': 'بيع',
      'purchase': 'شراء',
      'amount': 'المبلغ',
      'documentId': 'المعرّف',
      'invalidIdentifier': 'المعرّف غير صالح',
      'invalidAmount': 'المبلغ غير صالح',
      'deleteSaleTitle': 'حذف هذا البيع؟',
      'deleteSaleWarning':
          'هذا الإجراء ليس إلغاءً تجارياً وقد يُرفض عند وجود دفعات.',
      'no': 'لا',
      'preview': 'معاينة',
      'invoicePreview': 'معاينة الفاتورة',
      'printFormat': 'تنسيق الطباعة',
      'documentPreview': 'معاينة المستند',
      'article': 'المنتج',
      'unitPrice': 'سعر الوحدة',
      'total': 'المجموع',
      'client': 'العميل',
      'phone': 'الهاتف',
      'address': 'العنوان',
      'thankYou': 'شكراً لثقتكم',
      'companyName': 'EL AMINE',
      'companyNameAr': 'الأمين للمواد الغذائية وغير الغذائية',
      'defaultPrinter': 'الطابعة الافتراضية',
      'openPdfToPrint': 'فتح ملف PDF A4',
      'invoiceListHint': 'رقم الفاتورة أو العميل',
    },
    'en': {
      'saleDetail': 'Sale details',
      'invoiceDetail': 'Invoice details',
      'date': 'Date',
      'status': 'Status',
      'ticket': 'Ticket',
      'products': 'Products',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'tax': 'Tax',
      'totalTtc': 'Total incl. tax',
      'paid': 'Amount paid',
      'paidShort': 'Paid',
      'due': 'Balance due',
      'dueShort': 'Due',
      'paymentMethod': 'Payment method',
      'payments': 'Payments',
      'noPayment': 'No payment recorded.',
      'edit': 'Edit',
      'print': 'Print',
      'reprint': 'Print / Reprint',
      'payment': 'Payment',
      'invoice': 'Invoice',
      'viewPdf': 'View PDF',
      'delete': 'Delete',
      'retry': 'Retry',
      'paidStatus': 'Paid',
      'partialStatus': 'Partially paid',
      'unpaidStatus': 'Unpaid',
      'unreconciledStatus': 'To reconcile',
      'noPrinter': 'No printer is configured.',
      'configurePrinter': 'Configure a printer',
      'later': 'Later',
      'printFailed': 'Unable to print the invoice',
      'salePreserved': 'The sale remains recorded.',
      'sentToPrinter': 'Invoice sent to the printer. Check the paper output.',
      'newSale': 'New sale',
      'editSale': 'Edit sale',
      'clientSearch': 'Search client',
      'productSearch': 'Search product',
      'packaging': 'Packaging',
      'unit': 'Unit',
      'quantity': 'Quantity',
      'serverPrice': 'Server price',
      'addProduct': 'Add product',
      'payFull': 'Pay in full',
      'save': 'Save',
      'cash': 'Cash',
      'cheque': 'Cheque',
      'transfer': 'Bank transfer',
      'saleSaved': 'Sale saved successfully',
      'viewInvoice': 'View invoice',
      'addPayment': 'Record payment',
      'backSales': 'Back to sales',
      'selectClientProducts': 'Select the client and every product.',
      'invalidQuantity': 'Invalid quantity',
      'invalidPrice': 'Invalid price',
      'lineTotal': 'Line total',
      'displayedTotal': 'Displayed total',
      'newPayment': 'New payment',
      'sale': 'Sale',
      'purchase': 'Purchase',
      'amount': 'Amount',
      'documentId': 'Identifier',
      'invalidIdentifier': 'Invalid identifier',
      'invalidAmount': 'Invalid amount',
      'deleteSaleTitle': 'Delete this sale?',
      'deleteSaleWarning':
          'This action is not a business cancellation and may be rejected when payments exist.',
      'no': 'No',
      'preview': 'Preview',
      'invoicePreview': 'Invoice preview',
      'printFormat': 'Print format',
      'documentPreview': 'DOCUMENT PREVIEW',
      'article': 'Item',
      'unitPrice': 'Unit price',
      'total': 'Total',
      'client': 'Client',
      'phone': 'Phone',
      'address': 'Address',
      'thankYou': 'Thank you for your trust',
      'companyName': 'EL AMINE',
      'companyNameAr': 'الأمين للمواد الغذائية وغير الغذائية',
      'defaultPrinter': 'Default printer',
      'openPdfToPrint': 'Open A4 PDF',
      'invoiceListHint': 'Invoice number or client',
    },
  };
}
